version: '3.8'

services:
  measur-tools-suite:
    build: .
    container_name: measur-tools-suite-build
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        rm -rf /home/MEASUR-Tools-Suite/
        cp -r /MEASUR-Tools-Suite /home/MEASUR-Tools-Suite/
        
        mkdir -p /home/MEASUR-Tools-Suite/build-cpp/
        cd /home/MEASUR-Tools-Suite/build-cpp/
        cmake ..
        cmake --build . -j 8 
        
        mkdir -p /home/MEASUR-Tools-Suite/build-wasm/
        cd /home/MEASUR-Tools-Suite/build-wasm/
        source /home/emsdk/emsdk_env.sh
        emcmake cmake -D BUILD_WASM=ON ..
        emmake make -j 8
        
        cd /home/MEASUR-Tools-Suite/
        npm install
        npm run test-wasm
    volumes:
      - ../MEASUR-Tools-Suite:/MEASUR-Tools-Suite
    ports:
      # - "127.0.0.1:3000:3000"
      - "3000:3000"
    networks:
      - ts-net

networks:
  ts-net:
    name: ts-build-network
