services:
  measur-tools-suite:
    build: .
    container_name: measur-tools-suite-build
    restart: no
    command:
      - /bin/sh
      - -c
      - |
        rm -rf /home/MEASUR-Tools-Suite/build-cpp/* \
               /home/MEASUR-Tools-Suite/build-wasm/*
        
        cd /home/MEASUR-Tools-Suite/build-cpp/
        cmake ..
        cmake --build . -j 8
        
        cd /home/emsdk/
        ./emsdk install latest
        ./emsdk activate latest
        source /home/emsdk/emsdk_env.sh

        cd /home/MEASUR-Tools-Suite/build-wasm/
        emcmake cmake -D BUILD_WASM=ON ..
        emmake make -j 8
        
        cd /home/MEASUR-Tools-Suite/
        npm install
        sleep infinity
    volumes:
      - ../MEASUR-Tools-Suite:/home/MEASUR-Tools-Suite
      - ./build-cpp:/home/MEASUR-Tools-Suite/build-cpp
      - ./build-wasm:/home/MEASUR-Tools-Suite/build-wasm
    ports:
      - "3000:3000"
    networks:
      - mts-dev

networks:
  mts-dev:
    name: measur-tools-suite-dev-network
