name: CI/CD

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches:
      - "develop"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  issues:
    types:
      - "opened"
  workflow_dispatch:

jobs:
  util-add-project-issue:
    if: github.event_name == 'issues' && github.event.action == 'opened'
    uses: ./.github/workflows/util_add-new-issue-to-project.yml
    secrets:
      PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}

  quality:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/pr_quality.yml

  release-docs:
    needs: quality
    if: github.event_name == 'push' && (github.ref_name == 'develop' || github.ref_name == 'master')
    uses: ./.github/workflows/release_docs.yml

  release-package-beta:
    needs: quality
    if: >
      github.event_name == 'pull_request' && 
      github.base_ref == 'develop' && 
      github.event.pull_request.draft == false &&
      github.event.pull_request.head.repo.fork == false
    uses: ./.github/workflows/release_package.yml
    with:
      release_channel: beta
      wasm_artifact_name: verified-wasm-${{ github.sha }}
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  release-package-rc:
    needs: quality
    if: github.event_name == 'push' && github.ref_name == 'develop'
    uses: ./.github/workflows/release_package.yml
    with:
      release_channel: rc
      wasm_artifact_name: verified-wasm-${{ github.sha }}
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  release-package-latest:
    needs: quality
    if: github.event_name == 'push' && github.ref_name == 'master'
    uses: ./.github/workflows/release_package.yml
    with:
      release_channel: latest
      wasm_artifact_name: verified-wasm-${{ github.sha }}
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
