name: "Release: Docs"

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y doxygen
      - name: Generate docs
        run: doxygen Doxyfile
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./docs/html
          if-no-files-found: error
          retention-days: 3

  deploy_dev:
    if: github.ref_name == 'develop'
    needs: build
    runs-on: ['self-hosted', 'dev']
    env:
      APACHE_DIR: /var/www/html
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Deploy
        run: rsync -a --delete ./* $APACHE_DIR/docs/suite/

  deploy_prod:
    if: github.ref_name == 'master'
    needs: build
    runs-on: ['self-hosted', 'prod']
    env:
      APACHE_DIR: /var/www/html
      BACKUP_DIR: /opt/actions-runner/backups
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Deploy
        run: |
          tar -czf $BACKUP_DIR/docs_$(printf '%(%Y-%m-%d)T\n' -1)_${GITHUB_SHA::7}.tar.gz $APACHE_DIR/docs/suite
          rsync -a --delete ./* $APACHE_DIR/docs/suite/