name: "Release: Package"

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: false

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get Node version
        run: echo "BUILD_NODE_VER=$(grep -o -P -m 1 '(?<=node":\s").*(?=")' package.json)" >> $GITHUB_ENV

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.BUILD_NODE_VER }}
          cache: npm
          package-manager-cache: true
          cache-dependency-path: package-lock.json
          registry-url: https://registry.npmjs.org/

      - name: Setup Emscripten SDK
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: latest
          actions-cache-folder: "emsdk-cache"

      - name: Set package version
        id: pkg_version
        run: |
          package_version="$(node -p "require('./package.json').version")"
          if [[ ${GITHUB_REF_NAME} == "develop" ]]; then
            package_version="${package_version}-rc.${GITHUB_RUN_NUMBER}"
            npm --no-git-tag-version version "$package_version"
          fi
          echo "PKG_VERSION=$package_version" >> "$GITHUB_OUTPUT"

      - name: Build native package
        run: |
          cmake -S . -B buildcpp -DCMAKE_BUILD_TYPE=Release
          cmake --build buildcpp --config Release --target clean
          cmake --build buildcpp --config Release -j 12

      - name: Install npm dependencies
        run: npm ci

      - name: Build WASM package
        run: |
          emcmake cmake -DBUILD_WASM=ON .
          emmake make clean
          emmake make -j 12
          rm -f bin/measur_tools_suite.js
          rm -f bin/measur_tools_suite.wasm
          cp package.json bin/package.json

      - name: Publish release candidate to npm
        if: github.ref_name == 'develop'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish --tag rc

      - name: Publish release to npm
        if: github.ref_name == 'master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish --tag latest

      - name: Release gh release
        if: github.ref_name == 'master'
        uses: softprops/action-gh-release@v3
        env:
          VERSION: ${{ steps.pkg_version.outputs.PKG_VERSION }}
        with:
          name: MEASUR-Tools-Suite v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          target_commitish: master
          draft: true
          generate_release_notes: true
